name: Test package

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies and build package
        run: |
          pnpm --filter @nimpl/context --filter tests-base add react@canary react-dom@canary next@canary --no-lockfile
          pnpm --filter @nimpl/context --filter tests-base add @types/react@latest @types/react-dom@latest --save-dev --no-lockfile
          pnpm run build
        working-directory: ./package

      - name: Test package general
        run: |
          pnpm playwright install
          pnpm build
          pnpm test
        working-directory: ./tests/base

      - name: Set summary
        run: |
          NEXT_VERSION=$(node -p "require('next/package.json').version")
          echo "$NEXT_VERSION" >> $GITHUB_STEP_SUMMARY
        working-directory: ./tests/base
